version: '3.8'

volumes:
  cassandra-data:

services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
    networks:
      - service
    volumes:
      - cassandra-data:/data/db

networks:
  service:
    driver: bridge
